version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: ./src/main/java/com/tuvarna/geo
          target: /usr/src/geowebapp
          ignore:
            - node_modules/
    environment:
      - SPRING_PROFILES_ACTIVE=development
