version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./target:/usr/src/myapp/target
    #command: mvn spring-boot:run
# services:
#   postgres:
#     image: 'postgres:latest'
#     environment:
#       - 'POSTGRES_DB=mydatabase'
#       - 'POSTGRES_PASSWORD=secret'
#       - 'POSTGRES_USER=myuser'
#     ports:
#       - '5432'
